[SERVICE]
    Flush           5
    Daemon          Off
    Log_Level       info
    Parsers_File    /etc/fluent-bit/parsers.conf
    storage.path    /var/lib/fluent-bit/storage
    storage.sync    normal
